services:
  #better to use custom images later on, this will let use have custom stuff already prepared and easily shareable without changing all
  postgres:
    image: postgres:18-alpine
    container_name: postgres_db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
    ## add to the env the database to connect to and the various args such as user, creation of database if it doesn't exists probably better in the image
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret #switch this to use files, better secrecy 
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    networks:
      - database
      - pgadmin_net
  
  pgadmin:
    image: dpage/pgadmin4:9.10
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5252:80
    depends_on:
      - postgres
    networks:
      - pgadmin_net

  nginx:
    image: nginx:1.29.4-alpine
    container_name: nginx_proxy
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html
    ports:
      - 8080:80
    restart: always
    networks:
      - frontend
  
  app:
    container_name: app
    build: .
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: always
    networks:
      - database
      - frontend

networks:
  database:
    driver: bridge
  
  frontend:
    driver: bridge

  pgadmin_net:
    driver: bridge

volumes:
  db-data: