services:
  #better to use custom images later on, this will let use have custom stuff already prepared and easily shareable without changing all
  nginx:
    build: 
      context: ./nginx
    container_name: nginx_proxy
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static:/usr/share/nginx/html
    ports:
      - 8080:80
    restart: always
    networks:
      - frontend

  app:
    build: 
      context: ./main
    environment:
      NODE_ENV: production
      PORT: 3000
      GOOGLE_APPLICATION_CREDENTIALS: /gcp/creds.json
    restart: always
    volumes:
      - C:\Users\filip\AppData\Roaming\gcloud\application_default_credentials.json:/gcp/creds.json:ro
    networks:
      - database
      - frontend
      - backend
    
networks:
  database:
    driver: bridge
  
  frontend:
    driver: bridge

  pgadmin_net:
    driver: bridge

  backend:
    driver: bridge

volumes:
  db-data:

  pgadmin-data:

  redis-data: