services:
  #better to use custom images later on, this will let use have custom stuff already prepared and easily shareable without changing all
  postgres:
    build: 
      context: ./postgres
    container_name: postgres_db
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./postgres/.env
    ports:
      - 5432:5432
    networks:
      - database
      - pgadmin_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d lolbile"]
      interval: 2s
      timeout: 2s
      retries: 5
  
  pgadmin:
    build: 
      context: ./pgadmin
    container_name: pgadmin4
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - ./pgadmin/.env
    ports:
      - 6769:80
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pgadmin_net

  nginx:
    build: 
      context: ./nginx
    container_name: nginx_proxy
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static:/usr/share/nginx/html
    ports:
      - 8080:80
    restart: always
    networks:
      - frontend

  app:
    build: 
      context: ./main
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - database
      - frontend
      - backend
    deploy:
      replicas: 5
    
networks:
  database:
    driver: bridge
  
  frontend:
    driver: bridge

  pgadmin_net:
    driver: bridge

  backend:
    driver: bridge

volumes:
  db-data:

  pgadmin-data:

  redis-data: